changelog:
  use: github

  filters:
    exclude:
      - Merge pull request
      - Merge branch
      - Bump
builds:
- goos:
    - linux
    - darwin
    - windows
  goarch:
    - "386"
    - amd64
    - arm
    - arm64
